#ifndef __BMS_EVENT_H__
#define __BMS_EVENT_H__
#include "lsapi_event.h"

#define MENU_NETWORK_NOT_REGISTER                   (LS_API_EV_BASE+18) 
#define MENU_NETWORK_REGISTER                       (LS_API_EV_BASE+19)

#define BMS_GET_MQTT_INFO_ID	(CUSTOM_EVENT_BEGIN_ID + 1)
#define BMS_GET_BOARD_BASE_INFO_ID	(CUSTOM_EVENT_BEGIN_ID + 2)
#define BMS_GET_BOARD_DYNAMIC_INFO_ID	(CUSTOM_EVENT_BEGIN_ID + 3)
#define BMS_GET_EVENT_INFO_ID	(CUSTOM_EVENT_BEGIN_ID + 4)
#define BMS_GET_SAFE_EVENT_INFO_ID	(CUSTOM_EVENT_BEGIN_ID + 5)
#define BMS_SND_ACTION_FROM_PLATFORM_ID	(CUSTOM_EVENT_BEGIN_ID + 6)

#define BMS_START_MQTT_ID	(CUSTOM_EVENT_BEGIN_ID + 20)
#define BMS_MQTT_PUB_REALTIME_INFO_ID	(CUSTOM_EVENT_BEGIN_ID + 21)
#define BMS_MQTT_PUB_OTA_RESULT_ID	(CUSTOM_EVENT_BEGIN_ID + 22)
#define BMS_MQTT_SUB_INFO_ID	(CUSTOM_EVENT_BEGIN_ID + 23)
#define BMS_MQTT_PUB_BATINFO_INFO_ID	(CUSTOM_EVENT_BEGIN_ID + 24)
#define BMS_MQTT_PUB_SAFE_EVENT_INFO_ID	(CUSTOM_EVENT_BEGIN_ID + 25)
#define BMS_MQTT_PUB_BMS_OPERATION_REPLY_ID	(CUSTOM_EVENT_BEGIN_ID + 26)
#define BMS_MQTT_PUB_TRACKER_OPERATION_REPLY_ID	(CUSTOM_EVENT_BEGIN_ID + 27)
#define BMS_MQTT_PUB_TRACKER_OTA_REPLY_ID	(CUSTOM_EVENT_BEGIN_ID + 28)
#define BMS_MQTT_PUB_LIBSAFE_OTA_REPLY_ID	(CUSTOM_EVENT_BEGIN_ID + 29)
#define BMS_MQTT_PUB_QUERY_REPLY_ID	(CUSTOM_EVENT_BEGIN_ID + 30)
#define BMS_MQTT_PUB_BASE_INFO_ID	(CUSTOM_EVENT_BEGIN_ID + 31)

#endif	/*__BMS_EVENT_H__*/