/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed May 11 19:10:06 2022. */

#include "LibSafeTrackerMessage.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MeassageData_fields[4] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, MeassageData, header, header, &Header_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, MeassageData, data, header, &Any_fields),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, MeassageData, code, data, 0),
    PB_LAST_FIELD
};

const pb_field_t Header_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, Header, thingId, thingId, 0),
    PB_FIELD(  2, INT64   , SINGULAR, STATIC  , OTHER, Header, timestamp, thingId, 0),
    PB_LAST_FIELD
};

const pb_field_t TrackerBaseInfo_fields[8] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, TrackerBaseInfo, model, model, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, TrackerBaseInfo, manufacture, model, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, TrackerBaseInfo, imei, manufacture, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, TrackerBaseInfo, imsi, imei, 0),
    PB_FIELD(  5, STRING  , SINGULAR, STATIC  , OTHER, TrackerBaseInfo, mobile, imsi, 0),
    PB_FIELD(  6, STRING  , SINGULAR, STATIC  , OTHER, TrackerBaseInfo, trackerHardwareVersion, mobile, 0),
    PB_FIELD(  7, STRING  , SINGULAR, STATIC  , OTHER, TrackerBaseInfo, trackerSoftwareVersion, trackerHardwareVersion, 0),
    PB_LAST_FIELD
};

const pb_field_t TrackerRealTimeInfo_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, TrackerRealTimeInfo, batteryInfo, batteryInfo, &BatteryInfo_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, TrackerRealTimeInfo, gpsLocationInfo, batteryInfo, &GpsLocationInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t BatteryInfo_fields[14] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, BatteryInfo, batteryVoltage, batteryVoltage, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, BatteryInfo, batteryCurrent, batteryVoltage, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, BatteryInfo, batterySoc, batteryCurrent, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, BatteryInfo, batteryHardVersion, batterySoc, 0),
    PB_FIELD(  5, STRING  , SINGULAR, STATIC  , OTHER, BatteryInfo, batterySoftVersion, batteryHardVersion, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, BatteryInfo, batteryWorkMode, batterySoftVersion, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, BatteryInfo, batteryProtectCode, batteryWorkMode, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, BatteryInfo, batteryErrorCode, batteryProtectCode, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, BatteryInfo, batteryTemperatureMax, batteryErrorCode, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, BatteryInfo, batteryVoltageMax, batteryTemperatureMax, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, BatteryInfo, batteryVoltageMin, batteryVoltageMax, 0),
    PB_FIELD( 12, INT32   , SINGULAR, STATIC  , OTHER, BatteryInfo, mosStatus, batteryVoltageMin, 0),
    PB_FIELD( 13, INT32   , SINGULAR, STATIC  , OTHER, BatteryInfo, chargeCycleTime, mosStatus, 0),
    PB_LAST_FIELD
};

const pb_field_t GpsLocationInfo_fields[14] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, GpsLocationInfo, reportReason, reportReason, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, GpsLocationInfo, detStatus, reportReason, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, GpsLocationInfo, csq, detStatus, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, GpsLocationInfo, networkType, csq, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, GpsLocationInfo, locationMode, networkType, 0),
    PB_FIELD(  6, DOUBLE  , SINGULAR, STATIC  , OTHER, GpsLocationInfo, longitude, locationMode, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, GpsLocationInfo, longitudeDirection, longitude, 0),
    PB_FIELD(  8, DOUBLE  , SINGULAR, STATIC  , OTHER, GpsLocationInfo, latitude, longitudeDirection, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, GpsLocationInfo, latitudeDirection, latitude, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, GpsLocationInfo, gpsSpeed, latitudeDirection, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, GpsLocationInfo, gpsSignal, gpsSpeed, 0),
    PB_FIELD( 12, INT32   , SINGULAR, STATIC  , OTHER, GpsLocationInfo, satelliteNum, gpsSignal, 0),
    PB_FIELD( 13, INT32   , SINGULAR, STATIC  , OTHER, GpsLocationInfo, accuracy, satelliteNum, 0),
    PB_LAST_FIELD
};

const pb_field_t EventRequestData_fields[8] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, EventRequestData, batteryLowPowerEvent, batteryLowPowerEvent, &BatteryLowPowerEvent_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, EventRequestData, batteryFaultEvent, batteryLowPowerEvent, &BatteryFaultEvent_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, EventRequestData, batteryProtectEvent, batteryFaultEvent, &BatteryProtectEvent_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, EventRequestData, trackerFaultEvent, batteryProtectEvent, &TrackerFaultEvent_fields),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, EventRequestData, trackerResetEvent, trackerFaultEvent, &TrackerResetEvent_fields),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, EventRequestData, batterySafeEvent, trackerResetEvent, &BatterySafeEvent_fields),
    PB_FIELD(  7, INT64   , SINGULAR, STATIC  , OTHER, EventRequestData, eventTime, batterySafeEvent, 0),
    PB_LAST_FIELD
};

const pb_field_t BatteryLowPowerEvent_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, BatteryLowPowerEvent, batterySoc, batterySoc, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, BatteryLowPowerEvent, gpsLocationInfo, batterySoc, &GpsLocationInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t BatteryFaultEvent_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, BatteryFaultEvent, batteryErrorCode, batteryErrorCode, 0),
    PB_LAST_FIELD
};

const pb_field_t BatteryProtectEvent_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, BatteryProtectEvent, batteryProtectCode, batteryProtectCode, 0),
    PB_LAST_FIELD
};

const pb_field_t TrackerFaultEvent_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, TrackerFaultEvent, logDetail, logDetail, 0),
    PB_LAST_FIELD
};

const pb_field_t TrackerResetEvent_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, TrackerResetEvent, serviceId, serviceId, 0),
    PB_LAST_FIELD
};

const pb_field_t BatterySafeEvent_fields[18] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, BatterySafeEvent, batteryVoltage, batteryVoltage, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, batteryCurrent, batteryVoltage, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, batterySoc, batteryCurrent, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, batteryAh, batterySoc, 0),
    PB_FIELD(  5, INT32   , REPEATED, STATIC  , OTHER, BatterySafeEvent, cellV, batteryAh, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, chargeState, cellV, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, faultState3, chargeState, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, faultCellNumber3, faultState3, 0),
    PB_FIELD(  9, INT32   , REPEATED, STATIC  , OTHER, BatterySafeEvent, faultCellID3, faultCellNumber3, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, meanOCV, faultCellID3, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, oCVIntervalCNT, meanOCV, 0),
    PB_FIELD( 12, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, faultState2, oCVIntervalCNT, 0),
    PB_FIELD( 13, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, faultCellNumber2, faultState2, 0),
    PB_FIELD( 14, INT32   , REPEATED, STATIC  , OTHER, BatterySafeEvent, faultCellID2, faultCellNumber2, 0),
    PB_FIELD( 15, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, faultState1, faultCellID2, 0),
    PB_FIELD( 16, INT32   , SINGULAR, STATIC  , OTHER, BatterySafeEvent, faultCellNumber1, faultState1, 0),
    PB_FIELD( 17, INT32   , REPEATED, STATIC  , OTHER, BatterySafeEvent, faultCellID1, faultCellNumber1, 0),
    PB_LAST_FIELD
};

const pb_field_t OtaResponseData_fields[4] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, OtaResponseData, result, result, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, OtaResponseData, reason, result, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, OtaResponseData, slaveThingIds, reason, 0),
    PB_LAST_FIELD
};

const pb_field_t TrackerQuery_fields[6] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, TrackerQuery, base, base, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, TrackerQuery, realtime, base, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, TrackerQuery, log, realtime, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, TrackerQuery, config, log, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, TrackerQuery, bat, config, 0),
    PB_LAST_FIELD
};

const pb_field_t OtaAction_fields[4] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, OtaAction, trackerOTA, trackerOTA, &FirmwareInfo_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, OtaAction, bmsOTA, trackerOTA, &BmsOTA_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, OtaAction, libsafeOTA, bmsOTA, &LibsafeOTA_fields),
    PB_LAST_FIELD
};

const pb_field_t FirmwareInfo_fields[8] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, FirmwareInfo, model, model, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, FirmwareInfo, manufacture, model, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, FirmwareInfo, hardwareVersion, manufacture, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, FirmwareInfo, softwareVersion, hardwareVersion, 0),
    PB_FIELD(  5, STRING  , SINGULAR, STATIC  , OTHER, FirmwareInfo, url, softwareVersion, 0),
    PB_FIELD(  6, STRING  , SINGULAR, STATIC  , OTHER, FirmwareInfo, md5, url, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, FirmwareInfo, size, md5, 0),
    PB_LAST_FIELD
};

const pb_field_t BmsOTA_fields[8] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, BmsOTA, model, model, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, BmsOTA, manufacture, model, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, BmsOTA, hardwareVersion, manufacture, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, BmsOTA, softwareVersion, hardwareVersion, 0),
    PB_FIELD(  5, STRING  , SINGULAR, STATIC  , OTHER, BmsOTA, url, softwareVersion, 0),
    PB_FIELD(  6, STRING  , SINGULAR, STATIC  , OTHER, BmsOTA, md5, url, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, BmsOTA, size, md5, 0),
    PB_LAST_FIELD
};

const pb_field_t LibsafeOTA_fields[8] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, LibsafeOTA, model, model, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, LibsafeOTA, manufacture, model, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, LibsafeOTA, hardwareVersion, manufacture, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, LibsafeOTA, softwareVersion, hardwareVersion, 0),
    PB_FIELD(  5, STRING  , SINGULAR, STATIC  , OTHER, LibsafeOTA, url, softwareVersion, 0),
    PB_FIELD(  6, STRING  , SINGULAR, STATIC  , OTHER, LibsafeOTA, md5, url, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, LibsafeOTA, size, md5, 0),
    PB_LAST_FIELD
};

const pb_field_t TrackerOperation_fields[3] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, TrackerOperation, turnOffBms, turnOffBms, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, TrackerOperation, turnOffTracker, turnOffBms, 0),
    PB_LAST_FIELD
};

const pb_field_t BmsOperation_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, BmsOperation, action, action, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, BmsOperation, value, action, 0),
    PB_LAST_FIELD
};

const pb_field_t BatInfo_fields[3] = {
    PB_FIELD(  1, INT32   , REPEATED, STATIC  , FIRST, BatInfo, cellVol, cellVol, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, BatInfo, batteryTemp, cellVol, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MeassageData, header) < 65536 && pb_membersize(MeassageData, data) < 65536 && pb_membersize(TrackerRealTimeInfo, batteryInfo) < 65536 && pb_membersize(TrackerRealTimeInfo, gpsLocationInfo) < 65536 && pb_membersize(EventRequestData, batteryLowPowerEvent) < 65536 && pb_membersize(EventRequestData, batteryFaultEvent) < 65536 && pb_membersize(EventRequestData, batteryProtectEvent) < 65536 && pb_membersize(EventRequestData, trackerFaultEvent) < 65536 && pb_membersize(EventRequestData, trackerResetEvent) < 65536 && pb_membersize(EventRequestData, batterySafeEvent) < 65536 && pb_membersize(BatteryLowPowerEvent, gpsLocationInfo) < 65536 && pb_membersize(OtaAction, trackerOTA) < 65536 && pb_membersize(OtaAction, bmsOTA) < 65536 && pb_membersize(OtaAction, libsafeOTA) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MeassageData_Header_TrackerBaseInfo_TrackerRealTimeInfo_BatteryInfo_GpsLocationInfo_EventRequestData_BatteryLowPowerEvent_BatteryFaultEvent_BatteryProtectEvent_TrackerFaultEvent_TrackerResetEvent_BatterySafeEvent_OtaResponseData_TrackerQuery_OtaAction_FirmwareInfo_BmsOTA_LibsafeOTA_TrackerOperation_BmsOperation_BatInfo)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MeassageData, header) < 256 && pb_membersize(MeassageData, data) < 256 && pb_membersize(TrackerRealTimeInfo, batteryInfo) < 256 && pb_membersize(TrackerRealTimeInfo, gpsLocationInfo) < 256 && pb_membersize(EventRequestData, batteryLowPowerEvent) < 256 && pb_membersize(EventRequestData, batteryFaultEvent) < 256 && pb_membersize(EventRequestData, batteryProtectEvent) < 256 && pb_membersize(EventRequestData, trackerFaultEvent) < 256 && pb_membersize(EventRequestData, trackerResetEvent) < 256 && pb_membersize(EventRequestData, batterySafeEvent) < 256 && pb_membersize(BatteryLowPowerEvent, gpsLocationInfo) < 256 && pb_membersize(OtaAction, trackerOTA) < 256 && pb_membersize(OtaAction, bmsOTA) < 256 && pb_membersize(OtaAction, libsafeOTA) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MeassageData_Header_TrackerBaseInfo_TrackerRealTimeInfo_BatteryInfo_GpsLocationInfo_EventRequestData_BatteryLowPowerEvent_BatteryFaultEvent_BatteryProtectEvent_TrackerFaultEvent_TrackerResetEvent_BatterySafeEvent_OtaResponseData_TrackerQuery_OtaAction_FirmwareInfo_BmsOTA_LibsafeOTA_TrackerOperation_BmsOperation_BatInfo)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
